version: '2'

services:
  rancher:
    image: rancher/rancher:v2.7.s1-head
    restart: always
    ports:
    - "8080:8080/tcp"
    - "443:443/tcp"
    volumes:
    - "rancher-data:/var/lib/rancher"
    privileged: true

volumes:
  rancher-data: