version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: rancher-postgres
    environment:
      POSTGRES_USER: rancher
      POSTGRES_PASSWORD: rancherpass
      POSTGRES_DB: rancherdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rancher-network

  rancher:
    image: rancher/rancher:latest
    container_name: rancher-server
    depends_on:
      - postgres
    privileged: true
    environment:
      CATTLE_DB_CATTLE_DATABASE: postgres
      CATTLE_DB_CATTLE_POSTGRES_HOST: postgres
      CATTLE_DB_CATTLE_POSTGRES_PORT: 5432
      CATTLE_DB_CATTLE_POSTGRES_NAME: rancherdb
      CATTLE_DB_CATTLE_POSTGRES_USERNAME: rancher
      CATTLE_DB_CATTLE_POSTGRES_PASSWORD: rancherpass
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rancher-data:/var/lib/rancher
    networks:
      - rancher-network

volumes:
  postgres-data:
  rancher-data:

networks:
  rancher-network:
    driver: bridge
