version: '2'

services:
 rancher:
    image: rancher/rancher:latest
    container_name: rancher-server
    depends_on:
      - postgres
    privileged: true
    environment:
      CATTLE_DB_CATTLE_DATABASE: postgres
      CATTLE_DB_CATTLE_POSTGRES_HOST: postgres
      CATTLE_DB_CATTLE_POSTGRES_PORT: 5432
      CATTLE_DB_CATTLE_POSTGRES_NAME: rancherdb
      CATTLE_DB_CATTLE_POSTGRES_USERNAME: rancher
      CATTLE_DB_CATTLE_POSTGRES_PASSWORD: rancherpass
    ports:
      - "80:8081"
      - "443:443"
    volumes:
      - rancher-data:/var/lib/rancher
    privileged: true    
    networks:
      
