version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KC_VENDOR: POSTGRES
      KC_ADDR: postgres
      KC_DATABASE: keycloak
      KC_USER: admin
      KC_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [ "start-dev", "--http-port 7080", "--https-port 7443", "--import-realm" ]
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 7080:7080
      - 7443:7443
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge
