version: "2"

services:
  influxdb:
    image: influxdb:1.7
    restart: always
    ports:
     - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      INFLUXDB_DB: actualdb
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
    driver: local
  influxdb-storage:
    driver: local
  influxdb-config:
    driver: local
