version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/teste
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
        - DEFAULT_VHOST=/
        - DEFAULT_USER=user
        - DEFAULT_PASS=pass123  
    networks:
        - rabbitmq_networks

networks:
  rabbitmq_networks:
    driver: bridge
