version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /db-data/postgres
    volumes:
      - ~/db-data:/var/lib/postgresql/data/
      - ~/sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge